### ISSUE TITLE
Full Files

### ISSUE THREAD

**Issue by pnewell** [NicoleRauch/WaniKaniVocabJLPT#1]
Are you able to upload the full data files?

var JLPTN5Vocab = path.join(__dirname, 'n5-vocab-kanji-hiragana.txt');
var JLPTN4Vocab = path.join(__dirname, 'n4-vocab-kanji-hiragana.txt');
var JLPTN3Vocab = path.join(__dirname, 'n3-vocab-kanji-hiragana.txt');
var JLPTN2Vocab = path.join(__dirname, 'n2-vocab-kanji-hiragana.txt');
var JLPTN1Vocab = path.join(__dirname, 'n1-vocab-kanji-hiragana.txt');

var JLPTN5Kanji = path.join(__dirname, 'n5-kanji.txt');
var JLPTN4Kanji = path.join(__dirname, 'n4-kanji.txt');
var JLPTN3Kanji = path.join(__dirname, 'n3-kanji.txt');
var JLPTN2Kanji = path.join(__dirname, 'n2-kanji.txt');
var JLPTN1Kanji = path.join(__dirname, 'n1-kanji.txt');

Would be great to have access to these and/or the script you used to make them.

**Comment by NicoleRauch** [comment]
It's been a while 😁
I was very much out of the loop with WK, but I just pushed a new commit that contains the files. Maybe it's still useful for you...
